Modified deployment

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,6 +32,22 @@ jobs:
       - name: Build React App
         run: CI=false npm run build
       
+      - name: Check and Prepare Deployment Directory
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.CPANEL_HOST }}
+          username: ${{ secrets.CPANEL_USER }}
+          key: ${{ secrets.CPANEL_SSH_KEY }}
+          script: |
+            DEPLOY_PATH="/home/$CPANEL_USER/$DEPLOY_DIR"
+            if [ ! -d "$DEPLOY_PATH" ]; then
+              mkdir -p "$DEPLOY_PATH"
+              echo "Created deployment directory: $DEPLOY_PATH"
+            else
+              echo "Deployment directory already exists: $DEPLOY_PATH"
+            fi
+      
+
       - name: Upload Files to cPanel
         uses: appleboy/scp-action@v0.1.7
         with:
@@ -41,6 +57,20 @@ jobs:
           source: build/*
           target: "/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
 
+      - name: Check Deployment
+        uses: appleboy/ssh-action@v1.0.3
+        with:
+          host: ${{ secrets.CPANEL_HOST }}
+          username: ${{ secrets.CPANEL_USER }}
+          key: ${{ secrets.CPANEL_SSH_KEY }}
+          script: |
+            DEPLOY_PATH="home/$CPANEL_USER/$DEPLOY_DIR"
+            if [ "$(ls -A "$DEPLOY_PATH")" ]; then
+              echo "Deployment successful. Files are present in $DEPLOY_PATH"
+            else
+              echo "Deployment failed. No files found in $DEPLOY_PATH"
+              exit 1
+            fi
 
       - name: Fix Permissions
         uses: appleboy/ssh-action@v1.0.3
